import 'list_class.dart';

List<ListClass> allList = [
  ListClass(
    qn: '1',
    question:
        'Here have 3 soldiers. But here one soldier is enemy. Here have 3 pictures of those soldiers. See those Pictures carefully and tell who is the \"Enemy\".',
    ans: "3rd soldier",
    pic1: "Pic_1.png",
    pic2: "Pic_2.png",
    pic3: "Pic_3.png",
    pic4: "Pic_4.png",
    ans1: "1st soldier",
    ans2: "2nd soldier",
    ans3: "3rd soldier",
  ),
  ListClass(
    qn: '2',
    question:
        'There has a criminal in a prison. But he try to escape. So, he digged and create a tarminal. Before escape from the prison he put a hotdog into his bag. But the end of the tarminal there have 3 doors. At the 1st door there is a strict police man. At the 2nd door there is a dangerous ghost criminal. And the last door there is a hungry dog. So which door is best for the \"criminal\".',
    ans: "3rd door",
    pic1: "Pic_5.png",
    pic2: "Pic_6.png",
    pic3: "Pic_7.png",
    pic4: "Pic_8.png",
    ans1: "1st door",
    ans2: "2nd door",
    ans3: "3rd door",
  ),
  ListClass(
    qn: '3',
    question:
        'Sana took break & she went to Paris. After coming home she saw her jewelleries and money are stolen by someone. She immedietly call police and he asked who know about her trip. She tells her three friends know.Can you tell me who is the culprit?',
    ans: "1st friend",
    pic1: "Pic_14.png",
    pic2: "Pic_9.png",
    pic3: "Pic_10.png",
    pic4: "Pic_11.png",
    ans1: "1st friend",
    ans2: "2nd friend",
    ans3: "3rd friend",
  ),
  ListClass(
    qn: '4',
    question:
        'Rohan\'s school teacher was very clever. One day a external teacher visit their school and when he asked questions to students, everyone rises their hands. Then external feel happy. But Everyone don\'t know aboul all questions. so, what is the logic?',
    ans: "Hand logic",
    pic1: "Pic_12.png",
    pic2: "Pic_15.png",
    pic3: "Pic_16.png",
    pic4: "Pic_13.png",
    ans1: "Hand logic",
    ans2: "Guess logic",
    ans3: "Both",
  ),
  ListClass(
    qn: '5',
    question:
        'Maid was doing her work. Suddenly, she heard sound of gun-sort. Then she call her owner and detective. Owner and detective come at home same time and owner says to detective that someone shot his wife. Now detective understand who is the murderer. Now you tell me who is the murderer?',
    ans: "Husband",
    pic1: "Pic_17.png",
    pic2: "Pic_18.png",
    pic3: "Pic_19.png",
    pic4: "Pic_20.png",
    ans1: "Husband",
    ans2: "Maid",
    ans3: "Both",
  ),
  ListClass(
    qn: '6',
    question:
        ' Rohan & Rama\'s child & Raj & Sama\'s child are missing from last two nights. So, they go to police station for their children. Police tell them they rescued 8 children. They can indentify their child. Can you tell me who are their child?',
    ans: "C & F",
    pic1: "Pic_21.png",
    pic2: "Pic_22.png",
    pic3: "Pic_23.png",
    pic4: "Pic_24.1.png",
    ans1: "C & F",
    ans2: "A & E",
    ans3: "D & G",
  ),
  ListClass(
    qn: '7',
    question:
        ' Two friends are playing on a sea beach. Suddenly they see a bird which trapped inside a deep pipe. Then they tried to rescue the bird with a stik. But it\'s not easy. So, how they rescue the bird?',
    ans: "Using Sand",
    pic1: "Pic_25.png",
    pic2: "Pic_26.png",
    pic3: "Pic_27.png",
    pic4: "Pic_28.png",
    ans1: "Using Water",
    ans2: "Using Sand",
    ans3: "Using Stik",
  ),
];
